apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      containers:
      - name: lab-service
        image: ak2267/lab-service:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3004  